// Query TypeMap
import "@sanity/client";

/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/schema.json
export type AboutUs = {
  _id: string;
  _type: "aboutUs";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  body?: BlockContent;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  subtitle?: string;
  position?: number;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageAltText?: string;
  link?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Member = {
  _id: string;
  _type: "member";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  subtitle?: string;
  position?: number;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageAltText?: string;
  link?: string;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  startTime?: string;
  endTime?: string;
  venue?: string;
  city?: string;
  state?: string;
  admissionPrice?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  mainImageAltText?: string;
  details?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  eventDetailsButtonText?: string;
  eventDetailsButtonURL?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | AboutUs
  | SanityImageAssetReference
  | BlockContent
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | Member
  | Event
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: EVENT_QUERY
// Query: *[_type == "event" && slug.current == $slug][0] {    ...,  }
export type EVENT_QUERY_RESULT = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  startTime?: string;
  endTime?: string;
  venue?: string;
  city?: string;
  state?: string;
  admissionPrice?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  mainImageAltText?: string;
  details?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  eventDetailsButtonText?: string;
  eventDetailsButtonURL?: string;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: EVENTS_QUERY
// Query: *[_type == "event" && defined(slug.current) && defined(startTime)] {    ...,  } | order(startTime desc)
export type EVENTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  startTime?: string;
  endTime?: string;
  venue?: string;
  city?: string;
  state?: string;
  admissionPrice?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  mainImageAltText?: string;
  details?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  eventDetailsButtonText?: string;
  eventDetailsButtonURL?: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: UPCOMING_EVENTS_QUERY
// Query: *[_type == "event" && defined(slug.current) && defined(startTime) && endTime >= now()] {    ...,  } | order(startTime asc)
export type UPCOMING_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  startTime?: string;
  endTime?: string;
  venue?: string;
  city?: string;
  state?: string;
  admissionPrice?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  mainImageAltText?: string;
  details?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  eventDetailsButtonText?: string;
  eventDetailsButtonURL?: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PAST_EVENTS_QUERY
// Query: *[_type == "event" && defined(slug.current) && defined(startTime) && endTime < now()] {    ...,  } | order(startTime desc)
export type PAST_EVENTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  startTime?: string;
  endTime?: string;
  venue?: string;
  city?: string;
  state?: string;
  admissionPrice?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  mainImageAltText?: string;
  details?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  eventDetailsButtonText?: string;
  eventDetailsButtonURL?: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: ABOUT_US_QUERY
// Query: *[_type == "aboutUs"][0] {    title,    body  }
export type ABOUT_US_QUERY_RESULT = {
  title: string | null;
  body: BlockContent | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: MEMBERS_QUERY
// Query: *[_type == "member"] {    _id,    name,    subtitle,    position,    image,    imageAltText,    link  } | order(position asc)
export type MEMBERS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  subtitle: string | null;
  position: number | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  imageAltText: string | null;
  link: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PRODUCTS_QUERY
// Query: *[_type == "product"] {    _id,    name,    subtitle,    position,    image,    imageAltText,    link  } | order(position asc)
export type PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  subtitle: string | null;
  position: number | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  imageAltText: string | null;
  link: string | null;
}>;

declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "event" && slug.current == $slug][0] {\n    ...,\n  }\n': EVENT_QUERY_RESULT;
    '\n  *[_type == "event" && defined(slug.current) && defined(startTime)] {\n    ...,\n  } | order(startTime desc)\n': EVENTS_QUERY_RESULT;
    '\n  *[_type == "event" && defined(slug.current) && defined(startTime) && endTime >= now()] {\n    ...,\n  } | order(startTime asc)\n': UPCOMING_EVENTS_QUERY_RESULT;
    '\n  *[_type == "event" && defined(slug.current) && defined(startTime) && endTime < now()] {\n    ...,\n  } | order(startTime desc)\n': PAST_EVENTS_QUERY_RESULT;
    '\n  *[_type == "aboutUs"][0] {\n    title,\n    body\n  }\n': ABOUT_US_QUERY_RESULT;
    '\n  *[_type == "member"] {\n    _id,\n    name,\n    subtitle,\n    position,\n    image,\n    imageAltText,\n    link\n  } | order(position asc)\n': MEMBERS_QUERY_RESULT;
    '\n  *[_type == "product"] {\n    _id,\n    name,\n    subtitle,\n    position,\n    image,\n    imageAltText,\n    link\n  } | order(position asc)\n': PRODUCTS_QUERY_RESULT;
  }
}
